name: Deploy

env:
  EX_APP_DIR: ex_app

on:
  push:
    branches:
      - main
    paths:
      - ${{ env.EX_APP_DIR }}/**
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Run ls
      run: ls
