name: Deploy

env:
  EX_APP_DIR: ex_app

on:
  push:
    branches:
      - main
    paths:
      - "ex_app/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Run ls
      run: ls
